---
- name: Install Docker Deps
  yum:
    name: '{{ item }}'
    state: present
  loop: '{{ docker_deps }}'

- name: Add Docker Repo
  get_url:
    url: '{{ docker_repo.url }}'
    dest: '{{ docker_repo.dest }}'
  become: yes

- name: Install Docker
  package:
    name: '{{ docker_package }}'
    state: latest
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes
