- name: Install Common Packages
  yum:
    name: '{{ item }}'
    state: present
  loop: '{{ common_packages }}'

- name: Unpack .ssh directory
  unarchive:
    src: '{{ provision_ssh_file }}'
    dest: '{{ tmp_dir }}'

- name: Copy ssh content into ssh directory
  copy:
    src: '{{ item }}'
    dest: '{{ home_dir }}/.ssh'
  with_items:
    - '{{ tmp_dir }}/.ssh/id_rsa'
    - '{{ tmp_dir }}/.ssh/id_rsa.pub'
    - '{{ tmp_dir }}/.ssh/known_hosts'
